# Generated by Django 4.1.3 on 2022-11-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='title')),
                ('depth', models.FloatField(verbose_name='depth')),
                ('diagonal', models.FloatField(verbose_name='diagonal')),
                ('height', models.FloatField(verbose_name='height')),
                ('width', models.FloatField(verbose_name='width')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notebooks', to='notebooks.brand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'Notebook',
                'verbose_name_plural': 'Notebooks',
            },
        ),
    ]
